const words = {
    // car: 'автомобиль',
    // chair: 'стул',
    // day: 'день',
    // ear: 'ухо',
    // fear: 'страх',
    // fire: 'огонь',
    able: 'способный',
    about: 'о',
    above: 'выше',
    accept: 'принять',
    across: 'через',
    act: 'действовать',
    actually: 'на самом деле',
    add: 'добавлять',
    admit: 'признавать',
    afraid: 'испуганный',
    after: 'после',
    afternoon: 'полдень',
    again: 'снова',
    against: 'против',
    age: 'возраст',
    ago: 'назад',
    agree: 'соглашаться',
    ahead: 'предстоящий',
    air: 'воздух',
    all: 'все',
    allow: 'позволять',
    almost: 'почти',
    alone: 'один',
    along: 'вдоль',
    already: 'уже',
    alright: 'хорошо',
    also: 'также',
    although: 'хотя',
    always: 'всегда',
    amaze: 'удивлять',
    anger: 'злость',
    angry: 'злой',
    animal: 'животное',
    annoy: 'раздражать',
    another: 'другой',
    answer: 'отвечать',
    any: 'любой',
    anymore: 'больше',
    anyone: 'любой',
    anything: 'что-либо',
    anyway: 'в любом случае',
    apartment: 'квартира',
    apparently: 'видимо',
    appear: 'появляться',
    approach: 'подход',
    area: 'область',
    arm: 'рука',
    around: 'вокруг',
    arrive: 'приезжать',
    ask: 'просить',
    asleep: 'спящий',
    attack: 'атаковать',
    attempt: 'attempt',
    attention: 'внимание',
    aunt: 'тетя',
    avoid: 'избегать',
    away: 'далеко',
    baby: 'ребенок',
    back: 'назад',
    bad: 'плохой',
    bag: 'сумка',
    ball: 'мяч',
    band: 'группа',
    bar: 'бар',
    barely: 'едва',
    bathroom: 'ванная комната',
    beat: 'бить',
    beautiful: 'красивый',
    became: 'стал',
    because: 'потому что',
    become: 'становиться',
    bed: 'кровать',
    bedroom: 'спальня',
    before: 'до',
    begin: 'начинать',
    behind: 'позади',
    believe: 'верить',
    bell: 'колокол',
    beside: 'рядом',
    best: 'лучший',
    better: 'лучше',
    between: 'между',
    big: 'большой',
    bit: 'кусочек',
    bite: 'кусать',
    black: 'черный',
    blink: 'моргать',
    block: 'блокировать',
    blonde: 'блондинка',
    blood: 'кровь',
    blue: 'синий',
    blush: 'краснеть',
    body: 'тело',
    book: 'книга',
    bore: 'бурить',
    both: 'оба',
    bother: 'беспокоить',
    bottle: 'бутылка',
    bottom: 'нижний',
    box: 'коробка',
    boy: 'мальчик',
    boyfriend: 'парень',
    brain: 'мозг',
    break: 'перерыв',
    breakfast: 'завтрак',
    breath: 'дыхание',
    bright: 'яркий',
    bring: 'приносить',
    broke: 'сломанный',
    brother: 'брат',
    brown: 'коричневый',
    brush: 'щетка',
    build: 'строить',
    burn: 'гореть',
    burst: 'лопаться',
    bus: 'автобус',
    business: 'бизнес',
    busy: 'занятый',
    but: 'но',
    buy: 'купить',
}

export default words