const words = {
    able: 'способный',
    about: 'о',
    above: 'выше',
    accept: 'принять',
    across: 'через',
    act: 'действовать',
    actually: 'на самом деле',
    add: 'добавлять',
    admit: 'признавать',
    afraid: 'испуганный',
    after: 'после',
    afternoon: 'полдень',
    again: 'снова',
    against: 'против',
    age: 'возраст',
    ago: 'назад',
    agree: 'соглашаться',
    ahead: 'предстоящий',
    air: 'воздух',
    all: 'все',
    allow: 'позволять',
    almost: 'почти',
    alone: 'один',
    along: 'вдоль',
    already: 'уже',
    alright: 'хорошо',
    also: 'также',
    although: 'хотя',
    always: 'всегда',
    amaze: 'удивлять',
    anger: 'злость',
    angry: 'злой',
    animal: 'животное',
    annoy: 'раздражать',
    another: 'другой',
    answer: 'отвечать',
    any: 'любой',
    anymore: 'больше',
    anyone: 'любой',
    anything: 'что-либо',
    anyway: 'в любом случае',
    apartment: 'квартира',
    apparently: 'видимо',
    appear: 'появляться',
    approach: 'подход',
    area: 'область',
    arm: 'рука',
    around: 'вокруг',
    arrive: 'приезжать',
    ask: 'просить',
    asleep: 'спящий',
    attack: 'атаковать',
    attempt: 'пытаться',
    attention: 'внимание',
    aunt: 'тетя',
    avoid: 'избегать',
    away: 'далеко',
    baby: 'ребенок',
    back: 'назад',
    bad: 'плохой',
    bag: 'сумка',
    ball: 'мяч',
    band: 'группа',
    bar: 'бар',
    barely: 'едва',
    bathroom: 'ванная комната',
    beat: 'бить',
    beautiful: 'красивый',
    became: 'стал',
    because: 'потому что',
    become: 'становиться',
    bed: 'кровать',
    bedroom: 'спальня',
    before: 'до',
    begin: 'начинать',
    behind: 'позади',
    believe: 'верить',
    bell: 'колокол',
    beside: 'рядом',
    best: 'лучший',
    better: 'лучше',
    between: 'между',
    big: 'большой',
    bit: 'кусочек',
    bite: 'кусать',
    black: 'черный',
    blink: 'моргать',
    block: 'блокировать',
    blonde: 'блондинка',
    blood: 'кровь',
    blue: 'синий',
    blush: 'краснеть',
    body: 'тело',
    book: 'книга',
    bore: 'бурить',
    both: 'оба',
    bother: 'беспокоить',
    bottle: 'бутылка',
    bottom: 'нижний',
    box: 'коробка',
    boy: 'мальчик',
    boyfriend: 'парень',
    brain: 'мозг',
    break: 'перерыв',
    breakfast: 'завтрак',
    breath: 'дыхание',
    bright: 'яркий',
    bring: 'приносить',
    broke: 'сломанный',
    brother: 'брат',
    brown: 'коричневый',
    brush: 'щетка',
    build: 'строить',
    burn: 'гореть',
    burst: 'лопаться',
    bus: 'автобус',
    business: 'бизнес',
    busy: 'занятый',
    but: 'но',
    buy: 'купить',
    call: "вызов",
    calm: "спокойствие",
    came: "пришел",
    can: "может",
    "can't": "не мочь",
    car: "машина",
    card: "карта",
    care: "забота",
    carefully: "осторожно",
    carry: "нести",
    case: "случай",
    cat: "кот",
    catch: "ловить",
    caught: "пойманный",
    cause: "причина",
    cell: "клетка",
    chair: "стул",
    chance: "шанс",
    change: "изменять",
    chase: "гнаться",
    check: "проверять",
    cheek: "щека",
    chest: "грудь",
    child: "ребенок",
    children: "дети",
    chuckle: "смеяться",
    city: "город",
    class: "сорт",
    clean: "чистый",
    clear: "прозрачный",
    climb: "взбираться",
    close: "закрывать",
    clothes: "одежда",
    coffee: "кофе",
    cold:"холодный",
    college: "колледж",
    color: "цвет",
    come: "приходить",
    comment: "комментарий",
    complete: "полный",
    completely: "полностью",
    computer: "компьютер",
    concern: "беспокойство",
    confuse: "путать",
    consider: "учитывать",
    continue: "продолжать",
    control: "контроль",
    conversation: "беседа",
    cool: "прохладный",
    corner: "угол",
    couch: "диван",
    could: "мог",
    "couldn't": "не мог",
    counter: "прилавок",
    couple: "пара",
    course: "курс",
    cover: "крышка",
    crack: "трескаться",
    crazy: "сумасшедший",
    cross: "крест",
    crowd: "толпа",
    cry: "плакать",
    cup: "чашка",
    cut: "резать",
    cute: "милый",
    dad: "папа",
    damn: "проклятие",
    dance: "танцевать",
    dark: "темный",
    date: "дата",
    daughter: "дочь",
    day: "день",
    dead: "мертвый",
    deal: "иметь дело",
    dear: "дорогой",
    death: "смерть",
    decide: "решать",
    deep: "глубокий",
    definitely: "определенно",
    desk: "рабочий стол",
    did: "делал",
    "didn't": "не сделал",
    die: "умереть",
    different: "другой",
    dinner: "ужин",
    direction: "направление",
    disappear: "пропадать",
    do: "делать",
    doctor: "врач",
    does: "делает",
    "doesn't": "не делает",
    dog: "собака",
    "don't": "не",
    done: "сделанный",
    door: "дверь",
    doubt: "сомневаться",
    down: "вниз",
    drag: "тащить",
    draw: "рисовать",
    dream: "мечтать",
    dress: "одеваться",
    drink: "напиток",
    drive: "водить машину",
    drop: "уронить",
    drove: "ехал",
    dry: "сухой",
    during: "в течение",
    each: "каждый",
    ear: "ухо",
    early: "рано",
    easily: "легко",
    easy: "легкий",
    eat: "есть",
    edge: "край",
    either: "или",
    else: "еще",
    empty: "пустой",
    end: "конец",
    enjoy: "наслаждаться",
    enough: "достаточно",
    enter: "входить",
    entire: "весь",
    escape: "побег",
    especially: "особенно",
    even: "даже",
    evening: "вечер",
    eventually: "в конце концов",
    ever: "всегда",
    every: "каждый",
    everyone: "каждый",
    everything: "все",
    exactly: "точно",
    except: "кроме",
    excite: "возбуждать",
    exclaim: "восклицать",
    excuse: "извинение",
    expect: "ожидать",
    explain: "объяснять",
    expression: "выражение",
    eye: "глаз",
    eyebrow: "бровь",
    face: "лицо",
    fact: "факт",
    fall: "падать",
    family: "семья",
    far: "далеко",
    fast: "быстрый",
    father: "отец",
    fault: "вина",
    favorite: "любимый",
    fear: "страх",
    feel: "чувствовать",
    feet: "ноги",
    fell: "упал",
    few: "немного",
    field: "поле",
    fight: "драться",
    figure: "фигура",
    fill: "наполнять",
    finally: "окончательно",
    find: "находить",
    fine: "отлично",
    finger: "палец",
    finish: "заканчивать",
    fire: "огонь",
    first: "первый",
    fit: "соответствовать",
    five: "пять",
    fix: "исправить",
    flash: "вспышка",
    flip: "подбросить",
    floor: "пол",
    fly: "летать",
    focus: "фокус",
    follow: "следовать",
    food: "еда",
    foot: "ступня",
    for: "для",
    force: "сила",
    forget: "забывать",
    form: "форма",
    forward: "вперед",
    found: "найденный",
    four: "четыре",
    free: "бесплатно",
    friend: "друг",
    from: "от",
    front: "передний",
    frown: "хмуриться",
    full: "полный",
    fun: "веселье",
    funny: "забавный",
    further: "дальше",
    game: "игра",
    gasp: "вздохнуть",
    gave: "отдал",
    gaze: "взгляд",
    gently: "нежно",
    get: "получать",
    giggle: "хихикать",
    girl: "девочка",
    girlfriend: "подруга",
    give: "давать",
    given: "данный",
    glad: "радостный",
    glance: "взглянуть мельком",
    glare: "блики",
    glass: "стекло",
    go: "идти",
    god: "Бог",
    gone: "ушел",
    gonna: "собираюсь",
    good: "хороший",
    got: "получил",
    gotten: "получил",
    grab: "схватить",
    great: "большой",
    green: "зеленый",
    greet: "приветствовать",
    grey: "серый",
    grin: "ухмылка",
    grip: "схватить",
    groan: "стон",
    ground: "земля",
    group: "группа",
    grow: "расти",
    guard: "сторожить",
    guess: "предполагать",
    gun: "пистолет",
    guy: "парень",
    had: "имел",
    "hadn't": "не имел",
    hair: "волосы",
    half: "половина",
    hall: "зал",
    hallway: "коридор",
    hand: "рука",
    handle: "ручка",
    hang: "вешать",
    happen: "случаться",
    happy: "счастливый",
    hard: "жесткий",
    has: "имеет",
    hate: "ненавидеть",
    have: "иметь",
    "haven't": "нет",
    he: "он",
    "he'd": "он бы",
    he: "он",
    head: "голова",
    hear: "слышать",
    heard: "слышал",
    heart: "сердце",
    heavy: "тяжелый",
    held: "держал",
    hell: "ад",
    hello: "привет",
    help: "помощь",
    her: "ее",
    here: "здесь",
    herself: "себя",
    hey: "привет",
    hi: "привет",
    hide: "скрывать",
    high: "высокий",
    him: "ему",
    himself: "сам",
    his: "его",
    hit: "ударять",
    hold: "держать",
    home: "дом",
    hope: "надеяться",
    horse: "лошадь",
    hospital: "больница",
    hot: "горячий",
    hour: "час",
    house: "дом",
    how: "как",
    however: "однако",
    hug: "обнимать",
    huge: "огромный",
    huh: "хм",
    human: "человек",
    hundred: "сто",
    hung: "висит",
    hurry: "торопиться",
    hurt: "повредить",
}

export default words

const words_1000 = [
"call", "camera", "campaign", "can", "cancer", "candidate", "capital", "car", "card",
  "care", "career", "carry", "case", "catch", "cause", "cell", "center", "central", "century",
  "certain", "certainly", "chair", "challenge", "chance", "change", "character", "charge", "check",
  "child", "choice", "choose", "church", "citizen", "city", "civil", "claim", "class", "clear",
  "clearly", "close", "coach", "cold", "collection", "college", "color", "come", "commercial",
  "common", "community", "company", "compare", "computer", "concern", "condition", "conference",
  "Congress", "consider", "consumer", "contain", "continue", "control", "cost", "could", "country",
  "couple", "course", "court", "cover", "create", "crime", "cultural", "culture", "cup", "current",
  "customer", "cut", "dark", "data", "daughter", "day", "dead", "deal", "death", "debate",
  "decade", "decide", "decision", "deep", "defense", "degree", "Democrat", "democratic", "describe",
  "design", "despite", "detail", "determine", "develop", "development", "die", "difference",
  "different", "difficult", "dinner", "direction", "director", "discover", "discuss", "discussion",
  "disease", "do", "doctor", "dog", "door", "down", "draw", "dream", "drive", "drop", "drug",
  "during", "each", "early", "east", "easy", "eat", "economic", "economy", "edge", "education",
  "effect", "effort", "eight", "either", "election", "else", "employee", "end", "energy", "enjoy",
  "enough", "enter", "entire", "environment", "environmental", "especially", "establish", "even",
  "evening", "event", "ever", "every", "everybody", "everyone", "everything", "evidence", "exactly",
  "example", "executive", "exist", "expect", "experience", "expert", "explain", "eye", "face",
  "fact", "factor", "fail", "fall", "family", "far", "fast", "father", "fear", "federal", "feel",
  "feeling", "few", "field", "fight", "figure", "fill", "film", "final", "finally", "financial", "find", "fine", "finger", "finish", "fire", "firm", "first",
  "fish", "five", "floor", "fly", "focus", "follow", "food", "foot", "for", "force", "foreign",
  "forget", "form", "former", "forward", "four", "free", "friend", "from", "front", "full",
  "fund", "future", "game", "garden", "gas", "general", "generation", "get", "girl", "give",
  "glass", "go", "goal", "good", "government", "great", "green", "ground", "group", "grow",
  "growth", "guess", "gun", "guy", "hair", "half", "hand", "hang", "happen", "happy", "hard",
  "have", "he", "head", "health", "hear", "heart", "heat", "heavy", "help", "her", "here",
  "herself", "high", "him", "himself", "his", "history", "hit", "hold", "home", "hope", "hospital",
  "hot", "hotel", "hour", "house", "how", "however", "huge", "human", "hundred", "husband", "I",
  "idea", "identify", "if", "image", "imagine", "impact", "important", "improve", "in", "include",
  "including", "increase", "indeed", "indicate", "individual", "industry", "information", "inside",
  "instead", "institution", "interest", "interesting", "international", "interview", "into", "investment",
  "involve", "issue", "it", "item", "its", "itself", "job", "join", "just", "keep", "key", "kid",
  "kill", "kind", "kitchen", "know", "knowledge", "land", "language", "large", "last", "late",
  "later", "laugh", "law", "lawyer", "lay", "lead", "leader", "learn", "least", "leave", "left",
  "leg", "legal", "less", "let", "letter", "level", "lie", "life", "light", "like", "likely",
  "line", "list", "listen", "little", "live", "local", "long", "look", "lose", "loss", "lot",
  "love", "low", "machine", "magazine", "main", "maintain", "major", "majority", "make", "man",
  "manage", "management", "manager", "many", "market", "marriage", "material", "matter", "may",
  "maybe", "me", "mean", "measure", "media", "medical", "meet", "meeting", "member", "memory",
  "mention", "message", "method", "middle", "might", "military", "million", "mind", "minute",
  "miss", "mission", "model", "modern", "moment", "money", "month", "more", "morning", "most",
  "mother", "mouth", "move", "movement", "movie", "Mr", "Mrs", "much", "music", "must", "my",
  "myself", "name", "nation", "national", "natural", "nature", "near", "nearly", "necessary",
  "need", "network", "never", "new", "news", "newspaper", "next", "nice", "night", "no", "none",
  "nor", "north", "not", "note", "nothing", "notice", "now", "n't", "number", "occur", "of",
  "off", "offer", "office", "officer", "official", "often", "oh", "oil", "ok", "old", "on",
  "once", "one", "only", "onto", "open", "operation", "opportunity", "option", "or", "order",
  "organization", "other", "others", "our", "out", "outside", "over", "own", "owner", "page",
  "pain", "painting", "paper", "parent", "part", "participant", "particular", "particularly", "partner",
  "party", "pass", "past", "patient", "pattern", "pay", "peace", "people", "per", "perform",
  "performance", "perhaps", "period", "person", "personal", "phone", "physical", "pick", "picture",
  "piece", "place", "plan", "plant", "play", "player", "PM", "point", "police", "policy", "political",
  "politics", "poor", "popular", "population", "position", "positive", "possible", "power", "practice",
  "prepare", "present", "president", "pressure", "pretty", "prevent", "price", "private", "probably",
  "problem", "process", "produce", "product", "production", "professional", "professor", "program",
  "project", "property", "protect", "prove", "provide", "public", "pull", "purpose", "push", "put",
  "quality", "question", "quickly", "quite", "race", "radio", "raise", "range", "rate", "rather",
  "reach", "read", "ready", "real", "reality", "realize", "really", "reason", "receive", "recent",
  "recently", "recognize", "record", "red", "reduce", "reflect", "region", "relate", "relationship",
  "religious", "remain", "remember", "remove", "report", "represent", "Republican", "require",
  "research", "resource", "respond", "response", "responsibility", "rest", "result", "return", "reveal",
  "rich", "right", "rise", "risk", "road", "rock", "role", "room", "rule", "run", "safe", "same",
  "save", "say", "scene", "school", "science", "scientist", "score", "sea", "season", "seat",
  "second", "section", "security", "see", "seek", "seem", "sell", "send", "senior", "sense",
  "series", "serious", "serve", "service", "set", "seven", "several", "sex", "sexual", "shake",
  "share", "she", "shoot", "short", "shot", "should", "shoulder", "show", "side", "sign",
  "significant", "similar", "simple", "simply", "since", "sing", "single", "sister", "sit", "site",
  "situation", "six", "size", "skill", "skin", "small", "smile", "so", "social", "society",
  "soldier", "some", "somebody", "someone", "something", "sometimes", "son", "song", "soon", "sort",
  "sound", "source", "south", "southern", "space", "speak", "special", "specific", "speech", "spend",
  "sport", "spring", "staff", "stage", "stand", "standard", "star", "start", "state", "statement",
  "station", "stay", "step", "still", "stock", "stop", "store", "story", "strategy", "street",
  "strong", "structure", "student", "study", "stuff", "style", "subject", "success", "successful",
  "such", "suddenly", "suffer", "suggest", "summer", "support", "sure", "surface", "system", "table",
  "take", "talk", "task", "tax", "teach", "teacher", "team", "technology", "television", "tell",
  "ten", "tend", "term", "test", "than", "thank", "that", "the", "their", "them", "themselves",
  "then", "theory", "there", "these", "they", "thing", "think", "third", "this", "those", "though",
  "thought", "thousand", "threat", "three", "through", "throughout", "throw", "thus", "time", "to",
  "today", "together", "tonight", "too", "top", "total", "tough", "toward", "town", "trade",
  "traditional", "training", "travel", "treat", "treatment", "tree", "trial", "trip", "trouble",
  "true", "truth", "try", "turn", "TV", "two", "type", "under", "understand", "unit", "until",
  "up", "upon", "us", "use",
  "usually", "value", "various", "very", "victim", "view", "violence", "visit", "voice", "vote",
  "wait", "walk", "wall", "want", "war", "watch", "water", "way", "we", "weapon", "wear", "week",
  "weight", "well", "west", "western", "what", "whatever", "when", "where", "whether", "which",
  "while", "white", "who", "whole", "whom", "whose", "why", "wide", "wife", "will", "win", "wind",
  "window", "wish", "with", "within", "without", "woman", "wonder", "word", "work", "worker",
  "world", "worry", "would", "write", "writer", "wrong", "yard", "yeah", "year", "yes", "yet",
  "you", "young", "your", "yourself"
];
